name: Deploy via Dokploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Trigger Dokploy webhook
        run: |
          curl -k -X POST \
            https://dokploy.dom.local/api/deploy/Y5zV7srD5O1bxA5v1Zilw \
            -H "Content-Type: application/json" \
            -d '{
              "branch": "main",
              "repository": "'"${{ github.repository }}"'",
              "ref": "refs/heads/main,
              "sha": "'"${{ github.sha }}"'"
            }'
